### ISSUE TITLE
Xcode build error BoringSSL-GRPC "use of undeclared identifier 'SSL_get_secure_renegotiation_support'; did you mean 'GRPC_SHADOW_SSL_get_secure_renegotiation_support'?"

### ISSUE THREAD

**Issue by d2vydov** [grpc/grpc-swift#545]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

I getting an error with building project, after updating SwiftGRPC to 0.9.1 and gRPC to 1.19.0:
 
`/Users/***/***/Pods/BoringSSL-GRPC/ssl/t1_lib.cc:3224:9: Use of undeclared identifier 'SSL_get_secure_renegotiation_support'; did you mean 'GRPC_SHADOW_SSL_get_secure_renegotiation_support'?`

So, this pods I am using in my project:

```
pod 'SwiftGRPC', '0.9.1'
pod 'SwiftProtobuf', '1.5.0'
pod 'gRPC', '1.19.0'
pod 'gRPC-Core', '1.19.0'
pod 'gRPC-ProtoRPC', '1.19.0'
pod 'gRPC-RxLibrary', '1.19.0'
pod 'nanopb', '0.3.901'
pod 'Protobuf', '3.9.0'
```

In the` Podfile.lock`, BoringSSL-GRPC has below versions
```
- BoringSSL-GRPC (0.0.3):
    - BoringSSL-GRPC/Implementation (= 0.0.3)
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Implementation (0.0.3):
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Interface (0.0.3)

```

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   10.14.3                                                       |
| Swift Version                 |   5.0.1                                                       |
| Xcode Version                 |   10.3.0                                                       |
| gRPC-Swift Version            |   0.9.1                                                       |
| gRPC Version            |   1.19.0                                                      |
  </pre>
</details>

I've already tried:

- Clean project
- Clean derived data
- Remove CocoaPods cache
- Rebooting
- Pod install --repo-update
- Delete Pods & pod update
- Reinstall cocoapods
- Reinstall Xcode

etc.

Can you please help?

P.S. I don't know, maybe it's not an SwiftGRPC issue, but I didnt found BoringSSL-GRPC Project.

**Comment by MrMage** [comment]
The issue indeed sounds related to SwiftGRPC. However, I am using SwiftGRPC 0.9.1 through CocoaPods and it is working fine for me; could you try creating an empty project with only a `pod SwiftGRPC` dependency, and see if that compiles for you?

**Comment by d2vydov** [comment]
sure, just a second :)

**Comment by d2vydov** [comment]
oh, no, it doesn't. the same error. @MrMage do you know what the problem?

**Comment by d2vydov** [comment]
I've getting this Podfile.lock:
```

PODS:
  - BoringSSL-GRPC (0.0.3):
    - BoringSSL-GRPC/Implementation (= 0.0.3)
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Implementation (0.0.3):
    - BoringSSL-GRPC/Interface (= 0.0.3)
  - BoringSSL-GRPC/Interface (0.0.3)
  - gRPC-Core (1.19.0):
    - gRPC-Core/Implementation (= 1.19.0)
    - gRPC-Core/Interface (= 1.19.0)
  - gRPC-Core/Implementation (1.19.0):
    - BoringSSL-GRPC (= 0.0.3)
    - gRPC-Core/Interface (= 1.19.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.19.0)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - SwiftGRPC (0.9.1):
    - gRPC-Core (~> 1.19.0)
    - SwiftProtobuf (~> 1.5.0)
  - SwiftProtobuf (1.5.0)

DEPENDENCIES:
  - SwiftGRPC (= 0.9.1)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - BoringSSL-GRPC
    - gRPC-Core
    - nanopb
    - SwiftGRPC
    - SwiftProtobuf

SPEC CHECKSUMS:
  BoringSSL-GRPC: be3aaeecf82982187df61ccf8844f62ac75c1e32
  gRPC-Core: 8ce876480da74af2988f1466b8daa99b8f5c79bb
  nanopb: 9f8aa4fc4e9d32c345e927e12c7bd9c0ea088353
  SwiftGRPC: 4f0d3cf9749ca1bc07cf954aca8b0c53d49cb814
  SwiftProtobuf: 438e705e11916cdf614f5a9d172e950b217b2c74

PODFILE CHECKSUM: b45e3668edeb14cd18ef68970e6fbaae8f09f722

COCOAPODS: 1.7.5

```

**Comment by MrMage** [comment]
Weird, given that it works for me. Do you maybe have e.g. BoringSSL and/or gRPC installed through Homebrew as well? (I must admit that I'm only using the library for macOS, not iOS.)

Another thing you could try would be to depend on only on `pod gRPC-Core` instead. If that fails as well, you should probably file an issue with them.

**Comment by d2vydov** [comment]
I'm using the library for iOS only. Is it possible that the error occurs because some libs installed through homebrew?

**Comment by d2vydov** [comment]
yeah, `pod gRPC-Core` fails :(

**Comment by d2vydov** [comment]
added issue to gRPC-Core, https://github.com/grpc/grpc/issues/19908

so, I close this.

**Comment by d2vydov** [comment]
so, anyway, @MrMage, thank you for your help :)
