### ISSUE TITLE
Make failed on High Sierra (10.13.4), Xcode 9.1, version 0.3.3

### ISSUE THREAD

**Issue by edopelawi** [grpc/grpc-swift#205]
I'm not sure what happened, but the `make` script for version 0.3.3 failed after I upgraded to 10.13.14. Here's the log where it fails:

```
[project-path]/grpc-swift/Sources/CgRPC/src/core/lib/support/log_posix.c:66:13: error: missing '#include <time.h>'; definition of 'tm' must be imported from module 'Darwin.C.time' before it is required
  struct tm tm;
            ^
/Applications/Xcode9.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/time.h:74:8: note: previous definition is here
struct tm {
       ^
1 error generated.
```

Does anyone have experienced this or know the fix? Any help would be appreciated, thanks!

**Comment by MrMage** [comment]
This is a long shot, but could you try building from master instead of version 0.3.3?

**Comment by edopelawi** [comment]
It still produce the same error, both in Xcode 9.1 and 9.3.

**Comment by bootstraponline** [comment]
I'm on macOS 10.13.4 using Xcode 9.2 and it worked.

**Comment by edopelawi** [comment]
Thanks for sharing, @bootstraponline! I wonder where I went wrong, though...

**Comment by rebello95** [comment]
Are you still seeing this issue on 0.4.1?

**Comment by edopelawi** [comment]
@rebello95 haven't tried that one. I'll try that out!

**Comment by shengyang998** [comment]
Well, I hit this problem as well. System High Sierra (10.13.4), Xcode 9.3, version 0.4.2
Log: 
```log
While building module 'Darwin' imported from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb.h:65:
In file included from <module-includes>:355:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/ncurses.h:141:
/opt/local/include/unctrl.h:60:63: error: unknown type name 'SCREEN'
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                              ^
/opt/local/include/unctrl.h:60:53: error: function cannot return function type 'char *(int *, chtype)' (aka 'char *(int *, unsigned int)')
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                    ^
/opt/local/include/unctrl.h:60:54: error: a parameter list without types is only allowed in a function definition
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                     ^
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb_common.c:6:
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb_common.h:8:
/Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb.h:65:10: fatal error: could not build module 'Darwin'
#include <stdint.h>
 ~~~~~~~~^
4 errors generated.
While building module 'Darwin' imported from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb.h:65:
In file included from <module-includes>:355:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/ncurses.h:141:
/opt/local/include/unctrl.h:60:63: error: unknown type name 'SCREEN'
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                              ^
/opt/local/include/unctrl.h:60:53: error: function cannot return function type 'char *(int *, chtype)' (aka 'char *(int *, unsigned int)')
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                    ^
/opt/local/include/unctrl.h:60:54: error: a parameter list without types is only allowed in a function definition
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                     ^
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb_encode.c:6:
/Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb.h:65:10: fatal error: could not build module 'Darwin'
#include <stdint.h>
 ~~~~~~~~^
4 errors generated.
While building module 'Darwin' imported from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb.h:65:
In file included from <module-includes>:355:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/ncurses.h:141:
/opt/local/include/unctrl.h:60:63: error: unknown type name 'SCREEN'
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                              ^
/opt/local/include/unctrl.h:60:53: error: function cannot return function type 'char *(int *, chtype)' (aka 'char *(int *, unsigned int)')
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                    ^
/opt/local/include/unctrl.h:60:54: error: a parameter list without types is only allowed in a function definition
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                     ^
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb_decode.c:16:
/Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/third_party/nanopb/pb.h:65:10: fatal error: could not build module 'Darwin'
#include <stdint.h>
 ~~~~~~~~^
4 errors generated.
While building module 'Darwin' imported from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/include/grpc/impl/codegen/port_platform.h:180:
In file included from <module-includes>:355:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/ncurses.h:141:
/opt/local/include/unctrl.h:60:63: error: unknown type name 'SCREEN'
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                              ^
/opt/local/include/unctrl.h:60:53: error: function cannot return function type 'char *(int *, chtype)' (aka 'char *(int *, unsigned int)')
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                    ^
/opt/local/include/unctrl.h:60:54: error: a parameter list without types is only allowed in a function definition
NCURSES_EXPORT(NCURSES_CONST char *) NCURSES_SP_NAME(unctrl) (SCREEN*, chtype);
                                                     ^
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/src/core/tsi/transport_security_grpc.c:19:
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/include/src/core/tsi/transport_security_grpc.h:22:
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/include/grpc/slice_buffer.h:22:
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/include/grpc/slice.h:22:
In file included from /Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/include/grpc/impl/codegen/slice.h:22:
/Users/yjm/Downloads/grpc-swift-0.4.2/Sources/CgRPC/include/grpc/impl/codegen/port_platform.h:180:10: fatal error: could not build module 'Darwin'
#include <Availability.h>
 ~~~~~~~~^
4 errors generated.
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/yjm/Downloads/grpc-swift-0.4.2/.build/debug.yaml main -v output:


make: *** [all] Error 1
```

Are there any dependencies I need to install?

**Comment by tsabirgaliev** [comment]
@shengyang998 this is because you have `zlib` in macports. The fix is ugly: remove `pkgConfig: "zlib"` from `.build/checkouts/swift-nio-zlib-support.git--.../Package.swift`.

The issue is that `-I/opt/local/include` is added by `pkgConfig` option in response to "Where is zlib?" query, and it pulls in incompatible version of ncurses.

**Comment by moldabekov** [comment]
@shengyang998 I confirm that @tsabirgaliev 's  solution works. Mostly issue described above happens because of `pkg-config` from MacPorts passes wrong path for `CFLAGS`.

There are several ways to fix it (all of them ugly):
1. @tsabirgaliev solution - **most convenient** one. It's quickwin.
2. Pass `$PATH` variable without MacPorts directories (i.e. exclude all `/opt/...` entries from `$PATH`)
3. Uninstall zlib from MacPorts. This variant will also affect on other installed ports such as `curl`, `openssl` and so on.

**Comment by shengyang998** [comment]
Thanks a lot.  
@tsabirgaliev 's solution is good. 
Perhaps it would be a temporary workaround to add some `sed` command to remove that line in `Package.swift` automatically. A little wacky, though.

**Comment by tsabirgaliev** [comment]
@shengyang998 https://github.com/grpc/grpc-swift/pull/221 please also look at this PR

**Comment by MrMage** [comment]
Closing this due to inactivity.

**Comment by pushkarnk** [comment]
Another way to work around this compilation failure is using the  `-DNCURSES_UNCTRL_H_incl` option:
```
swift build -Xcc -DNCURSES_UNCTRL_H_incl
```
